version: "3"
services:
  config-service:
    image: twyanteng/config-service
    restart: always
    ports:
      - "8888:8888"

  zuul-service:
    image: twyanteng/zuul-service
    restart: always
    ports:
      - "8084:8084"

  todo-service:
    image: twyanteng/todo-service
    ports: 
      - "8082:8082"
    depends_on:
      - "mysql"

  user-service:
    image: twyanteng/user-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - "mysql"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    restart: always

  todo-js:
    image: twyanteng/todo-js
    ports:
      -  "81:81"
